name: bildAndTestSolution
description: 'build and test dotnet solution'

inputs:
  solution:
    required: true
    description: 'path to the solution file'
    type: string
  version-suffix:
    required: true
    description: 'the version suffix'
    type: string
  github_token:
    description: 'github_token'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'dotnet build without version-suffix'
      shell: bash
      if: ${{ inputs.version-suffix  == '' }}
      run: dotnet build "${{ inputs.solution }}" --configuration Release"

    - name: 'dotnet build with version-suffix: ${{ inputs.version-suffix }}'
      shell: bash
      if: ${{ inputs.version-suffix != '' }} 
      run: dotnet build "${{ inputs.solution }}" --configuration Release --version-suffix ${{ inputs.version-suffix }}"

    - name: 'dotnet test'
      shell: bash
      run: dotnet test "${{ inputs.solution }}"
